/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HaRouteImport } from './routes/ha'

const HaRoute = HaRouteImport.update({
  id: '/ha',
  path: '/ha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ha': typeof HaRoute
}
export interface FileRoutesByTo {
  '/ha': typeof HaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ha': typeof HaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ha'
  fileRoutesByTo: FileRoutesByTo
  to: '/ha'
  id: '__root__' | '/ha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HaRoute: typeof HaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ha': {
      id: '/ha'
      path: '/ha'
      fullPath: '/ha'
      preLoaderRoute: typeof HaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HaRoute: HaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
