/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HaRouteImport } from './routes/ha'
import { Route as IndexRouteImport } from './routes/index'

const HaRoute = HaRouteImport.update({
  id: '/ha',
  path: '/ha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ha': typeof HaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ha': typeof HaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ha': typeof HaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ha'
  id: '__root__' | '/' | '/ha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaRoute: typeof HaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ha': {
      id: '/ha'
      path: '/ha'
      fullPath: '/ha'
      preLoaderRoute: typeof HaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaRoute: HaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
